# Generated by Django 5.1 on 2024-09-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accaunt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='adress',
            field=models.CharField(default=23, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='phone',
            field=models.CharField(default=3, max_length=16),
            preserve_default=False,
        ),
    ]
