# Generated by Django 5.1 on 2024-09-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accaunt', '0002_myuser_adress_myuser_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=13)),
            ],
        ),
    ]
